In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print("1D array:")
print("Shape:", a.shape)
print("Size:", a.size)
print("Dimension:", a.ndim)
print("Length:", len(a))

b = np.array([[1, 2, 3], [4, 5, 6]])

print("\n2D array:")
print("Shape:", b.shape)
print("Size:", b.size)
print("Dimension:", b.ndim)
print("Length:", len(b))

c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("\n3D array:")
print("Shape:", c.shape)
print("Size:", c.size)
print("Dimension:", c.ndim)
print("Length:", len(c))


1D array:
Shape: (5,)
Size: 5
Dimension: 1
Length: 5

2D array:
Shape: (2, 3)
Size: 6
Dimension: 2
Length: 2

3D array:
Shape: (2, 2, 3)
Size: 12
Dimension: 3
Length: 2


In [ ]:
arr1 = np.arange(0, 10, 2)
print("arange:", arr1)

# random.randint
rand_int = np.random.randint(1, 100, size=5)
print("random.randint:", rand_int)

# random.rand
rand_arr = np.random.rand(3, 2)
print("random.rand:", rand_arr)

# linspace: Return evenly spaced numbers over a specified interval.
lin_space = np.linspace(0, 5, 10)
print("linspace:", lin_space)

# ones: Return a new array of given shape and type, filled with ones.
ones_arr = np.ones((2, 3))
print("ones:", ones_arr)

# zeros: Return a new array of given shape and type, filled with zeros.
zeros_arr = np.zeros((3, 2))
print("zeros:", zeros_arr)

# diag: Extract diagonal or construct a diagonal array.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal_elements = np.diag(arr)
print("diag:", diagonal_elements)

# sum: Sum of array elements over a given axis.
arr = np.array([[1, 2], [3, 4]])
print("sum:", np.sum(arr))

arr = np.array([3, 1, 5, 2, 8])
print("min:", np.min(arr))

print("max:", np.max(arr))

print("mean:", np.mean(arr))

arange: [0 2 4 6 8]
random.randint: [99 58 83 98 10]
random.rand: [[0.82138821 0.60564552]
 [0.73092496 0.42758126]
 [0.39820355 0.51576858]]
linspace: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
ones: [[1. 1. 1.]
 [1. 1. 1.]]
zeros: [[0. 0.]
 [0. 0.]
 [0. 0.]]
diag: [1 5 9]
sum: 10
min: 1
max: 8
mean: 3.8


In [ ]:
import numpy as np


num_students = 50
student_marks = np.random.randint(0, 101, size=num_students)

passed_students_count = np.sum(student_marks >= 30)


failed_students_marks = student_marks[student_marks < 30]

print("Number of students passed:", passed_students_count)
print("Marks of failed students:", failed_students_marks)

Number of students passed: 35
Marks of failed students: [ 5 24 11  8 13 23 10 11  1 11 28  6  2 13 23]


In [ ]:

import numpy as np
rand_arr = np.random.randint(1, 51, size=(2, 5))
print(rand_arr)


[[34 19 40 35  1]
 [ 1 38 35 10 30]]


In [7]:
import numpy as np
odd_numbers = np.arange(-29, 11, 2)
print("Array of odd numbers between -30 and 10:", odd_numbers)

Array of odd numbers between -30 and 10: [-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]
